# Generated by Django 3.2.3 on 2021-05-15 15:19

import computedfields.resolver
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('registration_number', models.PositiveBigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6)),
                ('date_of_admission', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_updated_on', models.DateField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=22, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'students',
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
